# 注册服务中心地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/

# 服务端口地址
server:
  port: 8003

# 本服务在注册中心的名称
spring:
  application:
    name: feign
  # 在监控中心注册
  boot:
      admin:
        client:
          instance:
            name: admin-server

# 断路器开关
feign:
  hystrix:
    enabled: true

# 对外公开所有端点，用于监控
management:
  endpoints:
    web:
      exposure:
        include: "*"




