# 注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/

# 服务端口地址
server:
  port: 8005


spring:
  # 服务在注册中心的名称
  application:
    name: config-server
  # 配置文件所在仓库
  cloud:
    config:
      server:
        git:
          # 仓库地址
          uri: https://github.com/Patrickleeee/springcloudDemo/
          # 仓库相对路径
          search-paths: repo
          # 公有仓库，不需要用户名和密码；私有仓库需要填写
          username:
          password:
      # 仓库分支
      label: master
